packages:
  - packages/*

catalog:
  "@eslint/js": ^10.0.1
  "@tailwindcss/postcss": ^4.3.3
  "@tanstack/eslint-plugin-query": ^5.102.1
  "@tanstack/react-query": ^5.102.1
  "@trivago/prettier-plugin-sort-imports": ^6.0.2
  "@types/node": ^26.2.0
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  classnames: ^2.5.1
  eslint: ^10.9.0
  eslint-config-next: 16.3.2
  eslint-config-prettier: ^10.1.8
  next-intl: ^4.13.7
  prettier: ^3.9.6
  react: 19.2.8
  react-dom: 19.2.8
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  typescript-eslint: ^8.67.0
  vite: ^8.2.2

allowBuilds:
  "@parcel/watcher": false
  "@swc/core": true
  esbuild: true
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 5760 # 4 days in minutes

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
