name: CI
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
env:
  HUSKY: 0
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm ci
      - name: Run linter
        run: pnpm lint
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm ci
      - name: Run tests
        run: pnpm test
